# Generated by Django 5.2.8 on 2026-05-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exit_exams", "0002_initial"),
        ("rag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aichatsession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aichatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="rag.aichatsession",
            ),
        ),
        migrations.AddField(
            model_name="generatedflashcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_flashcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedquizquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="rag.generatedquiz",
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_materials",
                to="exit_exams.course",
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_materials",
                to="exit_exams.domain",
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_materials",
                to="exit_exams.topic",
            ),
        ),
        migrations.AddField(
            model_name="materialsummary",
            name="material",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="rag.studymaterial",
            ),
        ),
        migrations.AddField(
            model_name="generatedquiz",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_quizzes",
                to="rag.studymaterial",
            ),
        ),
        migrations.AddField(
            model_name="generatedflashcard",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="rag.studymaterial",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="rag.studymaterial",
            ),
        ),
        migrations.AddField(
            model_name="aichatsession",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="rag.studymaterial",
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(fields=["owner"], name="rag_studyma_owner_i_b8b230_idx"),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["course"], name="rag_studyma_course__ba51dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["domain"], name="rag_studyma_domain__33633d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(fields=["topic"], name="rag_studyma_topic_i_9c7d73_idx"),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["processing_status"], name="rag_studyma_process_6782f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["material"], name="rag_documen_materia_1acf91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["qdrant_point_id"], name="rag_documen_qdrant__4f9592_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("material", "chunk_index")},
        ),
    ]
