# Generated by Django 5.2.8 on 2026-07-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="publish_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
