# Generated by Django 5.2.8 on 2026-05-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exit_exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attemptdetail",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="exit_exams.examattempt",
            ),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_exams",
                to="exit_exams.course",
            ),
        ),
        migrations.AddField(
            model_name="mockexam",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_exams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="mock_exam",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt",
                to="exit_exams.mockexam",
            ),
        ),
        migrations.AddField(
            model_name="mockexamquestion",
            name="mock_exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_questions",
                to="exit_exams.mockexam",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mockexamquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_exam_links",
                to="exit_exams.question",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="exit_exams.question",
            ),
        ),
        migrations.AddField(
            model_name="attemptdetail",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt_details",
                to="exit_exams.question",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="exit_exams.domain",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exit_exams.topic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="domain",
            unique_together={("course", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="mockexam",
            unique_together={("student", "course", "exam_number")},
        ),
        migrations.AlterUniqueTogether(
            name="mockexamquestion",
            unique_together={("mock_exam", "order"), ("mock_exam", "question")},
        ),
        migrations.AddIndex(
            model_name="attemptdetail",
            index=models.Index(
                fields=["question"], name="exit_exams__questio_462e92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attemptdetail",
            index=models.Index(
                fields=["is_correct"], name="exit_exams__is_corr_52b6da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attemptdetail",
            unique_together={("attempt", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("domain", "name")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["topic"], name="exit_exams__topic_i_587c04_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="exit_exams__difficu_510609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["bloom_level"], name="exit_exams__bloom_l_d4a362_idx"
            ),
        ),
    ]
