# Generated by Django 5.2.8 on 2026-05-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPdfImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="exam_imports/")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("past_exam", "Past Exam"),
                            ("mock_exam", "Mock Exam"),
                            ("practice", "Practice"),
                            ("other", "Other"),
                        ],
                        default="mock_exam",
                        max_length=30,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("needs_review", "Needs Review"),
                            ("approved", "Approved"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=30,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_pdf_imports",
                        to="exit_exams.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_exam_pdfs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.PositiveIntegerField(blank=True, null=True)),
                ("question_text", models.TextField()),
                ("option_a", models.TextField(blank=True)),
                ("option_b", models.TextField(blank=True)),
                ("option_c", models.TextField(blank=True)),
                ("option_d", models.TextField(blank=True)),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, help_text="A, B, C, or D", max_length=1
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "bloom_level",
                    models.CharField(
                        choices=[
                            ("knowledge", "Knowledge"),
                            ("comprehension", "Comprehension"),
                            ("application", "Application"),
                            ("analysis", "Analysis"),
                        ],
                        default="knowledge",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_question",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_extracted_question",
                        to="exit_exams.question",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_questions",
                        to="exit_exams.domain",
                    ),
                ),
                (
                    "exam_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_questions",
                        to="exit_exams.exampdfimport",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_questions",
                        to="exit_exams.topic",
                    ),
                ),
            ],
        ),
    ]
