# Generated by Django 5.2.8 on 2026-05-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0003_exampdfimport_extractedquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("total_questions", models.PositiveIntegerField(default=100)),
                ("duration_minutes", models.PositiveIntegerField(default=180)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_blueprints",
                        to="exit_exams.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course__name", "title"],
                "unique_together": {("course", "title")},
            },
        ),
        migrations.CreateModel(
            name="ExamBlueprintDomainRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_questions", models.PositiveIntegerField()),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_rules",
                        to="exit_exams.examblueprint",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_rules",
                        to="exit_exams.domain",
                    ),
                ),
            ],
            options={
                "unique_together": {("blueprint", "domain")},
            },
        ),
    ]
