# Generated by Django 5.2.8 on 2026-06-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0004_examblueprint_examblueprintdomainrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="examblueprint",
            name="bloom_distribution",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ExamBlueprintTopicRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_count", models.PositiveIntegerField()),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_rules",
                        to="exit_exams.examblueprint",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_rules",
                        to="exit_exams.topic",
                    ),
                ),
            ],
            options={
                "unique_together": {("blueprint", "topic")},
            },
        ),
    ]
