# Generated by Django 5.2.8 on 2026-07-02 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0007_question_approval_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examblueprint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_blueprints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="difficulty_distribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"easy": 30, "medium": 50, "hard": 20}',
            ),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="marks_per_question",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="pass_percentage",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("blueprint_changed", "Blueprint Changed"),
                            ("assignment_changed", "Assignment Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="e.g. question, blueprint, assignment", max_length=50
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("previous_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="exit_exams__entity__166432_idx",
                    ),
                    models.Index(
                        fields=["user"], name="exit_exams__user_id_fc0dcd_idx"
                    ),
                    models.Index(
                        fields=["action"], name="exit_exams__action_01f559_idx"
                    ),
                    models.Index(
                        fields=["-timestamp"], name="exit_exams__timesta_b29085_idx"
                    ),
                ],
            },
        ),
    ]
