# Generated by Django 5.2.8 on 2026-07-13 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0009_add_submitted_status_and_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="originating_pdf_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_questions",
                to="exit_exams.exampdfimport",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("imported", "Imported")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
