# Generated by Django 5.2.8 on 2026-07-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0010_question_approved_at_question_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("blueprint_changed", "Blueprint Changed"),
                    ("assignment_changed", "Assignment Changed"),
                    ("system_settings_updated", "System Settings Updated"),
                    ("user_deactivated", "User Deactivated"),
                    ("user_reactivated", "User Reactivated"),
                    ("password_reset_by_admin", "Password Reset By Admin"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_passing_score", models.PositiveIntegerField(default=50)),
                (
                    "default_exam_duration_minutes",
                    models.PositiveIntegerField(default=60),
                ),
                ("max_battle_participants", models.PositiveIntegerField(default=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
