# Generated by Django 5.2.8 on 2026-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_exams", "0011_alter_auditlog_action_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="mastery_minimum_attempts",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="mastery_threshold_accuracy",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="quiz_unlock_score",
            field=models.PositiveIntegerField(default=70),
        ),
    ]
