# Generated by Django 5.2.8 on 2026-05-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("exit_exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinessscore",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readiness_scores",
                to="exit_exams.course",
            ),
        ),
    ]
