# Generated by Django 5.2.8 on 2026-05-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0002_initial"),
        ("exit_exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinessscore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readiness_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spacedrepetitionqueue",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaced_repetition_items",
                to="exit_exams.question",
            ),
        ),
        migrations.AddField(
            model_name="spacedrepetitionqueue",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaced_repetition_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spacedrepetitionqueue",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaced_repetition_items",
                to="exit_exams.topic",
            ),
        ),
        migrations.AddField(
            model_name="studenttopicperformance",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_topic_performances",
                to="exit_exams.domain",
            ),
        ),
        migrations.AddField(
            model_name="studenttopicperformance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_performances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studenttopicperformance",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_topic_performances",
                to="exit_exams.topic",
            ),
        ),
        migrations.AddIndex(
            model_name="readinessscore",
            index=models.Index(
                fields=["student", "course"], name="analytics_r_student_9091e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="readinessscore",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="spacedrepetitionqueue",
            index=models.Index(
                fields=["student", "next_review_date"],
                name="analytics_s_student_f9a32f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spacedrepetitionqueue",
            index=models.Index(fields=["topic"], name="analytics_s_topic_i_9120d4_idx"),
        ),
        migrations.AddIndex(
            model_name="spacedrepetitionqueue",
            index=models.Index(
                fields=["is_active"], name="analytics_s_is_acti_a42977_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spacedrepetitionqueue",
            unique_together={("student", "question")},
        ),
        migrations.AddIndex(
            model_name="studenttopicperformance",
            index=models.Index(
                fields=["student", "topic"], name="analytics_s_student_410a34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studenttopicperformance",
            index=models.Index(
                fields=["domain"], name="analytics_s_domain__281322_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studenttopicperformance",
            unique_together={("student", "topic")},
        ),
    ]
