# Generated by Django 5.2.8 on 2026-07-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_phase1_analytics_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("mock_available", "Mock Available"),
                    ("weak_topic", "Weak Topic"),
                    ("battle_invite", "Battle Invite"),
                    ("material_uploaded", "Material Uploaded"),
                    ("weekly_reminder", "Weekly Reminder"),
                    ("learning_path_ready", "Learning Path Ready"),
                    ("learning_step_unlocked", "Learning Step Unlocked"),
                    ("learning_path_completed", "Learning Path Completed"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=150)),
                ("subtopic", models.CharField(blank=True, max_length=150)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("current_step", models.CharField(default="summary", max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("flashcards", "Flashcards"),
                            ("quiz", "Quiz"),
                            ("mini_mock", "Mini Mock"),
                        ],
                        max_length=15,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="analytics.learningpath",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="learningpath",
            index=models.Index(
                fields=["student", "status"], name="analytics_l_student_6a9a1f_idx"
            ),
        ),
    ]
