# Generated by Django 5.2.8 on 2026-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_alter_focussession_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
